#!/usr/bin/env python3

import sys
import os

if len(sys.argv) < 2:
    NAME = ""
else:
    NAME = sys.argv[1]

project_folders = [f for f in os.listdir(".") if os.path.isdir(f)]
folder_numbers = [int(f.split("_")[0]) for f in project_folders]
highest_folder = max(folder_numbers)
NUM = highest_folder + 1
NUM_STR = str(NUM).zfill(2)

FOLDERNAME = f"{NUM_STR}{'_' + NAME if NAME else ''}"
FOLDER = f"{FOLDERNAME}/"

main_template = """// {FOLDER}{FILE}

fn main() {{
    println!("Hello, {FILE}!");
}}
"""

templates = {
    "main.rs": main_template,
}

# Create folder
os.mkdir(FOLDER)
print(f"Created project {FOLDER}")

for file, template in templates.items():
    with open(FOLDER + file, "w+") as f:
        f.write(
            template.format(NUM=NUM,
                            NUM_STR=NUM_STR,
                            FOLDERNAME=FOLDERNAME,
                            FOLDER=FOLDER,
                            FILE=file))
        print(f"Created file {FOLDER}{file}")

print(f"\nDone! Use this command to enter and start editing!\n$ cd {FOLDER}")

# If in editor mode
if "-e" in sys.argv or "--editor" in sys.argv:
    os.system(f"$EDITOR {FOLDER}main.rs")
