#!/usr/bin/env python3

import sys
import os

if len(sys.argv) < 2:
    NAME = ""
else:
    NAME = sys.argv[1]

project_folders = [
    f for f in os.listdir(".") if os.path.isdir(f) and f.startswith("project_")
]
folder_numbers = [int(f.split("_")[1]) for f in project_folders]
highest_folder = max(folder_numbers)
NUM = highest_folder + 1
NUM_STR = str(NUM).zfill(2)

FOLDERNAME = f"project_{NUM_STR}{'_' + NAME if NAME else ''}"
FOLDER = f"{FOLDERNAME}/"

# Create folder
os.system(f"cargo new {FOLDERNAME}")

print(
    f"\nDone! Use this command to enter and start editing!\n$ cd {FOLDER}src")

# If in editor mode
if "-e" in sys.argv or "--editor" in sys.argv:
    os.system(f"$EDITOR {FOLDER}src/main.rs")
